apiVersion: v1
kind: Secret
metadata:
  name: reporting-seeder-secret
  namespace: reporting-seeder
  labels:
    app: reporting-seeder
    part-of: reporting-seeder
stringData:
  DB_PASSWORD: postgres
