apiVersion: v1
kind: Service
metadata:
  name: reporting-seeder
  namespace: reporting-seeder
spec:
  type: ClusterIP
  selector:
    app: reporting-seeder
  ports:
    - name: http
      port: 80
      targetPort: 8080
