apiVersion: v1
kind: ServiceAccount
metadata:
  name: reporting-seeder
  namespace: reporting-seeder
  # If using IRSA, set the annotation below to the IAM role ARN for the service account
  # annotations:
  #   eks.amazonaws.com/role-arn: arn:aws:iam::<ACCOUNT_ID>:role/reporting-seeder-service-account-role
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reporting-seeder
  namespace: reporting-seeder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reporting-seeder
  template:
    metadata:
      labels:
        app: reporting-seeder
    spec:
      serviceAccountName: reporting-seeder
      containers:
        - name: reporting-seeder
          image: 270022076279.dkr.ecr.us-gov-west-1.amazonaws.com/reporting-seeder:latest
          envFrom:
            - configMapRef:
                name: reporting-seeder-config
            - secretRef:
                name: reporting-seeder-secret
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: "reporting_seeder.settings"
          # No container ports or HTTP probes: reporting_seeder does not expose an HTTP server.
