apiVersion: v1
kind: ConfigMap
metadata:
  name: airflow-control-plane-config
  namespace: airflow
data:
  ETL_PACKAGES_ROOT: "/app/packages"
  AIRFLOW_DAGS_DIR: "/opt/airflow/dags"
  AIRFLOW__CORE__DAGS_FOLDER: "/opt/airflow/dags"
  AIRFLOW__CORE__LOAD_EXAMPLES: "False"
  AIRFLOW__CORE__EXECUTOR: "LocalExecutor"
  AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: "postgresql+psycopg2://airflow:airflow@postgres:5432/airflow"
