apiVersion: v1
kind: Service
metadata:
  name: observability-jobs
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: observability-jobs
  ports:
    - name: http
      port: 80
      targetPort: 8080
