apiVersion: v1
kind: Secret
metadata:
  name: pipeline-processing-secret
  namespace: pipeline-processing
  labels:
    app: pipeline-processing
    component: sns-listener
    part-of: pipeline-processing
stringData:
  DB_PASSWORD: postgres
