apiVersion: batch/v1
kind: Job
metadata:
  name: pipeline-processing-run-once
  namespace: pipeline-processing
spec:
  backoffLimit: 1
  template:
    metadata:
      labels:
        job: pipeline-processing-run
    spec:
      serviceAccountName: pipeline-processing
      restartPolicy: Never
      containers:
        - name: pipeline-processing
          image: 270022076279.dkr.ecr.us-gov-west-1.amazonaws.com/pipeline-processing:latest
          command:
            - python
            - -m
            - pipeline_processing.cli.main
            - run
            - hello_world
          envFrom:
            - configMapRef:
                name: pipeline-processing-config
            - secretRef:
                name: pipeline-processing-secret
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: "pipeline_processing.settings"
            - name: PORT
              value: "8080"
          # No probes for job
