apiVersion: v1
kind: Service
metadata:
  name: sns-listener
  namespace: pipeline-processing
spec:
  type: LoadBalancer
  selector:
    app: pipeline-processing-sns
  ports:
    - name: http
      port: 80
      targetPort: 8080
