[tool.poetry]
name = "data-pipeline"
version = "0.1.0"
description = "Combined transforms + ingestion runtime lane"
authors = ["Admin <admin@example.com>"]
readme = "README.md"
packages = [{include = "data_pipeline", from = "src"}]

[tool.poetry.dependencies]
python = "^3.10"
etl-core = {path = "../etl_core", develop = true}
django = {version = "^4.2", optional = true}
# Local development
# etl-database-schema = {path = "../../../../benchmark/repositories/etl-database-schema", develop = true, optional = true}
# Production / CI
etl-database-schema = {git = "git@gitlab.dev-benchmarkanalytics.com:etl/etl-database-schema.git", rev = "v0.3.3", optional = true}

[tool.poetry.extras]
db = ["etl-database-schema", "django"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
