apiVersion: v1
kind: Secret
metadata:
  name: file-processing-secret
  namespace: file-processing
  labels:
    app: file-processing
    component: sns-listener
    part-of: file-processing
stringData:
  DB_PASSWORD: postgres
