apiVersion: v1
kind: ConfigMap
metadata:
  name: file-processing-config
  namespace: file-processing
  labels:
    app: file-processing
    component: sns-listener
    part-of: file-processing

data:
  DB_HOST: host.docker.internal
  DB_PORT: "5432"
  DB_NAME: postgres
  DB_USER: postgres
  ENVIRONMENT: production
  S3_SOURCE_BUCKET: ignored
  S3_DESTINATION_BUCKET: ignored
  AGENCY_S3_SLUG: ignored
